import type { Concert } from "./types";

export const CONCERTS_DATA: Concert[] = [
  {
    id: "postmalone",
    name: "Post Malone Presents The BIG ASS Stadium World Tour",
    venueName: "ราชมังคลากีฬาสถาน",
    venueQuery: "Rajamangala National Stadium Bangkok",
    doorTime: "17:00 น.",
    showTime: "19:00 น.",
    isOutdoor: true,
    rounds: [
      { key: "single", label: "วันอังคารที่ 22 กันยายน 2569", date: "2026-09-22T19:00:00+07:00" },
    ],
    prices: [
      { zone: "VIP Premium Package (ที่นั่ง E1H-E1L)", price: 13400, type: "VIP", color: "#2563EB", perks: "รวมบัตรที่นั่งโซน E1H/E1I/E1J/E1K/E1L ใกล้เวทีที่สุดในทุกแพ็กเกจ", hasSoundcheck: false, hasEarlyEntry: false },
      { zone: "VIP Early Entry Package (ยืน SL/SR)", price: 12100, type: "VIP", color: "#EAB308", perks: "สิทธิ์เข้าคิวโซนยืนก่อนใคร แต่ไม่มีพื้นที่เฉพาะกำหนดตายตัวในผัง", hasSoundcheck: false, hasEarlyEntry: true },
      { zone: "ยืน SL/SR", price: 5500, type: "Standing", color: "#93C5FD", perks: "โซนยืนหน้าสเตจ ราคาเดียวทั้งฝั่งซ้ายและขวา" },
      { zone: "ที่นั่ง E1 (วงในสุด)", price: 6800, type: "Seated", color: "#60A5FA", perks: "ที่นั่งวงในติดสนาม มองเห็นเวทีชัดที่สุดในกลุ่มที่นั่ง" },
      { zone: "ที่นั่ง E2 (วงกลาง)", price: 4800, type: "Seated", color: "#3B82F6", perks: "ที่นั่งวงกลาง คุ้มค่าที่สุดในกลุ่มที่นั่ง" },
      { zone: "ที่นั่ง E3/S1/S2/N1/N2 (วงนอก)", price: 2800, type: "Seated", color: "#1E3A8A", perks: "ที่นั่งวงนอกและฝั่งข้างสนาม ราคาประหยัดที่สุด" },
    ],
    hotels: [
      { id: "pm1", name: "Baan Thai Boutique", dist: "~0.72 กม.", rating: 4.8, price: 3200, mapQuery: "Baan Thai Boutique Bangkok", reason: "ที่พักบูทีคระดับ 5 ดาว ใกล้ราชมังคลาที่สุดในลิสต์ เดินถึงสนามได้สบาย", image: "https://ak-d.tripcdn.com/images/1mc1312000aespg85476D_R_960_660_R5_D.jpg", bookingUrl: "https://www.agoda.com/baan-thai-boutique-hotel/hotel/bangkok-th.html" },
      { id: "pm2", name: "Regent Ramkhamhaeng 22", dist: "~0.97 กม.", rating: 4.0, price: 1300, mapQuery: "Regent Ramkhamhaeng 22 Hotel Bangkok", reason: "ห้องพักกว้างขวาง มีที่จอดรถเยอะ ใกล้ราชมังคลาเดินทางสะดวก", image: "https://ak-d.tripcdn.com/images/1mc5e12000ia46tk1934F_R_960_660_R5_D.jpg", bookingUrl: "https://www.agoda.com/regent-ramkhamhaeng-22/hotel/bangkok-th.html" },
      { id: "pm3", name: "Livotel Hotel Hua Mak Bangkok", dist: "~1.7 กม.", rating: 4.2, price: 1600, mapQuery: "Livotel Hotel Hua Mak Bangkok", reason: "มีบริการเช็คอินด่วนแม้กลับดึก พร้อมสระว่ายน้ำและฟิตเนส เหมาะพักหลังคอนจบดึก", image: "https://ak-d.tripcdn.com/images/1mc4v12000guebddtEE78_R_500_400_R5.webp", bookingUrl: "https://www.agoda.com/livotel-hotel-hua-mak-bangkok/hotel/bangkok-th.html" },
      { id: "pm4", name: "Mintel Huamark", dist: "~2 กม.", rating: 4.3, price: 900, mapQuery: "Mintel Huamark Hotel Bangkok", reason: "งบประหยัดที่สุดในลิสต์ ห้องพักดีไซน์โมเดิร์น มีที่จอดรถและร้านสะดวกซื้อใกล้เคียง", image: "https://ak-d.tripcdn.com/images/0582412000mg32h751841_R_960_660_R5_D.jpg", bookingUrl: "https://www.agoda.com/mintel/hotel/bangkok-th.html" },
    ],
    transit: {
      public: "ARL: ลงสถานีหัวหมาก (A4) หรือสถานีรามคำแหง ประตู 1 → ต่อแท็กซี่/มอเตอร์ไซค์/รถเมล์/สองแถวเข้าสนาม | BTS: ลงพญาไท → ต่อ ARL → หัวหมาก (A4) หรือรามคำแหง ประตู 1 | MRT สีน้ำเงิน: ลงเพชรบุรี → ต่อ ARL มักกะสัน → หัวหมาก หรือรามคำแหง | MRT สีเหลือง: ลงมหาดไทย หรือลาดพร้าว 101 → ต่อรถเข้าสนาม | รถเมล์ที่ผ่านสนาม: สาย 22, 60, 71, 92, 93, 95ก, 115, 126, 137, 168, 545",
      boat: "ขึ้นเรือโดยสารคลองแสนแสบ ลงที่ท่าเรือมหาวิทยาลัยรามคำแหง หรือท่าเรือมหาดไทย → เดินตามถนนรามคำแหงและข้ามสะพานเข้าสู่สนามราชมังคลากีฬาสถาน",
      driving: "ที่จอดรถรอบสนามมีหลายจุด เช่น เทสโก้ โลตัส บางกะปิ (~1,170 คัน) เดอะมอลล์ บางกะปิ (~3,000 คัน) และเดอะไนน์ พระราม 9 (~500 คัน) แนะนำมาก่อนเวลาเพราะรถติดหนักช่วงเลิกงาน",
      grab: "ตั้งจุดรับ-ส่งไว้ที่ห้างใกล้เคียงแทนหน้าสนามตรง เพื่อเลี่ยงความแน่นช่วงคนออกพร้อมกันหลังโชว์จบ",
      returnNote: "หลังจบการแสดง หน้าสนามราชมังคลา ถนนรามคำแหง มีบริการรถสองแถวและมอเตอร์ไซค์รับส่ง ARL หัวหมาก / MRT พระราม 9 (มีค่าบริการ) คอนสเตเดียมกลางแจ้งมักเลิกดึก เผื่อแผนสำรองถ้ารถไฟฟ้าใกล้ปิด แนะนำพักค้างคืนใกล้สนามถ้าเดินทางไกล",
    },
    weatherNote: "22 กันยายนยังอยู่ในช่วงฤดูฝนของกรุงเทพฯ และราชมังคลาเป็นสเตเดียมกลางแจ้ง (อัฒจันทร์ส่วนใหญ่ไม่มีหลังคาคลุม) โอกาสเจอฝนตกช่วงเย็นมีค่อนข้างสูง แนะนำพกร่มพับหรือเสื้อกันฝนแบบพกพาติดตัวไว้เผื่อฉุกเฉิน",
    checklistExtra: [
      { text: "ร่มพับหรือเสื้อกันฝนแบบพกพา (สนามกลางแจ้ง ก.ย. ฝนตกได้ตลอด)", pending: false },
      { text: "หมวก/แว่นกันแดดถ้าไปถึงก่อนพระอาทิตย์ตก", pending: false },
    ],
  },
  {
    id: "xg",
    name: "XG WORLD TOUR : THE CORE IN BANGKOK",
    venueName: "อิมแพ็ค อารีน่า เมืองทองธานี",
    venueQuery: "Impact Arena Muang Thong Thani",
    doorTime: "18:00 น.",
    showTime: "19:00 น.",
    isOutdoor: false,
    rounds: [
      { key: "sun", label: "วันอาทิตย์ที่ 19 กรกฎาคม 2569", date: "2026-07-19T19:00:00+07:00" },
    ],
    prices: [
      { zone: "VVIP – Xtraordinary Version X", price: 7800, type: "VIP", color: "#EF4444", perks: "บัตรนั่งโซน VVIP ใกล้สเตจที่สุด + Soundcheck + Send-off + ป้ายห้อยคอ Tour + โฟโต้การ์ด Exclusive + ของที่ระลึก", hasSoundcheck: true, hasEarlyEntry: false },
      { zone: "VIP2 – Xtraordinary Version G", price: 6500, type: "VIP", color: "#EC4899", perks: "บัตรนั่งโซน VIP2 + Soundcheck + ป้ายห้อยคอ Tour + โฟโต้การ์ด Exclusive + ของที่ระลึก", hasSoundcheck: true, hasEarlyEntry: false },
      { zone: "โซน VIP1, VIP3, A1-A3", price: 5500, type: "Seated", color: "#F97316", perks: "ที่นั่งข้างสเตจและโซน A รอบ Floor มองเห็นสมาชิก XG ทั้ง 7 คนชัดเจน" },
      { zone: "โซน SF-SJ (Level 1 กลาง)", price: 5000, type: "Seated", color: "#A3E635", perks: "ที่นั่งโซน S ด้านหน้า Level 1 มุมมองครอบคลุมทั้งเวที" },
      { zone: "โซน SB-SE, SK-SN (Level 2)", price: 4500, type: "Seated", color: "#14B8A6", perks: "ที่นั่งโซน S Level 2 ฝั่งซ้ายและขวา มุมสูงเห็นบรรยากาศทะเลไฟ" },
      { zone: "โซน C-G, O-R (อัฒจันทร์)", price: 3500, type: "Seated", color: "#818CF8", perks: "ที่นั่งอัฒจันทร์ฝั่งข้าง เห็นทั้งเวทีและ Formation ของวง" },
      { zone: "โซน B, H-N, S, T (Level 3 วงนอก)", price: 2500, type: "Seated", color: "#4338CA", perks: "ราคาประหยัดที่สุด เห็นภาพรวมทั้งฮอลล์ บรรยากาศทะเลไฟสวยมาก" },
    ],
    hotels: [
      { id: "xg1", name: "Novotel Bangkok IMPACT", dist: "0.2 กม. (สกายวอล์กตรงเข้าฮอลล์)", rating: 4.5, price: 3500, mapQuery: "Novotel Bangkok Impact", reason: "เชื่อมสกายวอล์กตรงเข้าประตูฮอลล์ เลี่ยงฝนกรกฎาคมและรถติดได้เต็มที่ ปลอดภัยที่สุดสำหรับขากลับดึก", image: "https://www.ahstatic.com/photos/8059_ho_00_p_1024x768.jpg", bookingUrl: "https://www.agoda.com/novotel-bangkok-impact-hotel/hotel/bangkok-th.html" },
      { id: "xg2", name: "ibis Bangkok IMPACT", dist: "0.4 กม.", rating: 4.2, price: 1800, mapQuery: "ibis Bangkok Impact", reason: "ราคาคุ้มค่าระดับกลาง เดินถึงฮอลล์ได้สบาย ทางเดินมีแสงสว่างดีตลอดคืน", image: "https://d2e5ushqwiltxm.cloudfront.net/wp-content/uploads/sites/162/2026/06/04051759/Exterior_1.jpg", bookingUrl: "https://www.agoda.com/ibis-bangkok-impact/hotel/bangkok-th.html" },
      { id: "xg3", name: "Popular Condo Ville (ตึก C3)", dist: "~1.2 กม.", rating: 3.8, price: 850, mapQuery: "Popular Condo Ville Muang Thong Thani", reason: "ที่พักงบประหยัดที่สุด แฟนคอน J-pop ไปพักรวมกันที่นี่บ่อยมาก ใกล้ร้านอาหารตึกป๊อปปูล่า", image: "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=700&q=80&fit=crop", bookingUrl: "https://www.agoda.com/great-location-at-impact-arena-muangthong-thani/hotel/nonthaburi-th.html" },
      { id: "xg4", name: "Amari Don Muang Airport", dist: "~9.5 กม. (นั่งรถ 20-25 นาที)", rating: 4.8, price: 2400, mapQuery: "Amari Don Muang Airport Bangkok", reason: "รีวิวดีที่สุดในระดับพรีเมียม เหมาะถ้าเดินทางต่อสนามบินดอนเมืองวันรุ่งขึ้น เลี่ยงย่านเมืองทองที่รถแน่น", image: "https://media.onyx-hospitality.com/-/media/project/amari/amari-don-muang-airport-bangkok/special-offers/outdoor-swimming-pool_sun-loungers.jpg", bookingUrl: "https://www.agoda.com/amari-don-muang-airport-bangkok-hotel/hotel/bangkok-th.html" },
    ],
    transit: {
      bts: "นั่ง BTS สายสีชมพู (Pink Line) ลงที่ สถานีเมืองทองธานี (MT01) → เปลี่ยนขบวนเข้า สถานีอิมแพ็คเมืองทองธานี → เดินผ่านทางเชื่อม IMPACT CHALLENGER HALL 1 → THE PORTAL → IMPACT ARENA",
      public: "รถเมล์สาย 166 จากอนุสาวรีย์ชัยฯ ฝั่งเกาะพหลโยธิน ผ่านหน้า IMPACT ARENA โดยตรง | รถเมล์สาย 52 จากอนุสาวรีย์ชัยฯ ต่อรถสองแถว | รถตู้เมืองทองธานีจากอนุสาวรีย์ชัยฯ ฝั่งเกาะพหลโยธิน | รถตู้เมืองทองธานีจาก BTS หมอชิต ฝั่งจตุจักร | ช่วงงาน J-pop รถรับ-ส่งพิเศษมักเปิดเพิ่มเติม ติดตามประกาศจากผู้จัด",
      driving: "ขับมาตามถนนแจ้งวัฒนะ หรือทางด่วนศรีรัช เข้า IMPACT ARENA เมืองทองธานี จอดได้ที่ลานจอดฝั่ง Challenger หรือลานจอดหน้าอารีน่า แนะนำมาก่อนประตูเปิดอย่างน้อย 1.5 ชม.",
      grab: "ตั้งจุดรับ-ส่งที่ลานจอดฝั่ง Challenger เพื่อเลี่ยงความแน่นหน้าฮอลล์หลัก ขากลับคิว Grab จะพีคมาก แนะนำรอในร้านอาหารป๊อปปูล่า 30-45 นาทีก่อน",
      returnNote: "คอน XG มักเลิกราว 21:00-21:30 น. BTS สายสีชมพูปิดราวๆ 24:00 น. เผื่อเวลาเดินออกจากฮอลล์ 10-15 นาที ถ้านัดรวมกับเพื่อน ALPHAZ แนะนำรอในร้านอาหารป๊อปปูล่าให้คนบางลงก่อน",
    },
    weatherNote: "กรกฎาคมอยู่ในช่วงฤดูฝนของกรุงเทพฯ แม้ IMPACT ARENA จะเป็นฮอลล์ในร่มและมีแอร์เย็น แต่การเดินทางไป-กลับอาจเจอฝน แนะนำพกร่มพับสำรองไว้ ในฮอลล์อาจเย็นมาก แนะนำพกเสื้อกันหนาวบางๆ ติดตัว",
    checklistExtra: [
      { text: "แท่งไฟ ALPHAZ ชาร์จแบตเต็มก่อนเข้างาน", pending: false },
      { text: "Merch XG THE CORE ที่ซื้อไว้ล่วงหน้า", pending: false },
    ],
  },
  {
    id: "babymonster",
    name: "2026-27 BABYMONSTER WORLD TOUR [CHOOM]",
    venueName: "อิมแพ็ค อารีน่า เมืองทองธานี",
    venueQuery: "Impact Arena Muang Thong Thani",
    doorTime: "16:30 น.",
    showTime: "18:00 น.",
    isOutdoor: false,
    rounds: [
      { key: "sat", label: "วันเสาร์ที่ 7 พฤศจิกายน 2569", date: "2026-11-07T18:00:00+07:00" },
      { key: "sun", label: "วันอาทิตย์ที่ 8 พฤศจิกายน 2569", date: "2026-11-08T18:00:00+07:00" },
    ],
    prices: [
      { zone: "VIP (V1-V3)", price: 7300, type: "VIP", color: "#38BDF8", perks: "โซนติดสเตจกลาง สิทธิ์ลุ้นรับชม Soundcheck และ VIP Pass คล้องคอที่ระลึกเฉพาะโซนนี้", hasSoundcheck: true, hasEarlyEntry: false },
      { zone: "โซน A (A1-A5)", price: 6300, type: "Seated", color: "#FB923C", perks: "ที่นั่งกึ่งเวทีชั้นล่าง เกาะขอบระยะประชิด มองเห็นทุกมุมชัด" },
      { zone: "โซน S แดง (SB-SD, SL-SN)", price: 5800, type: "Seated", color: "#EF4444", perks: "ที่นั่งชั้น Level 3 แถวหน้า บรรยากาศดี มองเห็นทั้งเวทีหลัก" },
      { zone: "โซน S น้ำเงิน (SE-SF, SJ-SK)", price: 5300, type: "Seated", color: "#3B82F6", perks: "ที่นั่งกึ่งกลางฮอลล์ ระยะห่างพอดี คุ้มค่าเรื่องมุมมอง" },
      { zone: "โซน SG-SI เหลืองทอง", price: 4800, type: "Seated", color: "#EAB308", perks: "ที่นั่งกลางฮอลล์ตรงหน้าเวที ราคาคุ้มค่าคุ้มราคาสุด" },
      { zone: "Level 4 เขียว (B-E, Q-T)", price: 3800, type: "Seated", color: "#22C55E", perks: "ที่นั่งอัฒจันทร์บนสุด เห็นภาพรวมทั้งฮอลล์ ทะเลแท่งไฟสวยงาม" },
      { zone: "ยืนพื้น/ริมนอก โซนชมพู", price: 2800, type: "Standing", color: "#EC4899", perks: "ประหยัดสุด ได้บรรยากาศยืนโบกไปกับเพลง เดินออกง่ายเลี่ยงรถติด" },
    ],
    hotels: [
      { id: "h1", name: "Novotel Bangkok IMPACT", dist: "0.2 กม. (สกายวอล์กตรงเข้าฮอลล์)", rating: 4.5, price: 3500, mapQuery: "Novotel Bangkok Impact", reason: "เชื่อมสกายวอล์กตรงเข้าประตูฮอลล์ เลี่ยงฝนและรถติดได้เต็มที่ ปลอดภัยที่สุดสำหรับขากลับดึก", image: "https://www.ahstatic.com/photos/8059_ho_00_p_1024x768.jpg", bookingUrl: "https://www.agoda.com/novotel-bangkok-impact-hotel/hotel/bangkok-th.html" },
      { id: "h2", name: "ibis Bangkok IMPACT", dist: "0.4 กม.", rating: 4.2, price: 1800, mapQuery: "ibis Bangkok Impact", reason: "ราคาคุ้มค่าระดับกลาง เดินถึงฮอลล์ได้สบาย ทางเดินมีแสงสว่างดีตลอดคืน", image: "https://d2e5ushqwiltxm.cloudfront.net/wp-content/uploads/sites/162/2026/06/04051759/Exterior_1.jpg", bookingUrl: "https://www.agoda.com/ibis-bangkok-impact/hotel/bangkok-th.html" },
      { id: "h3", name: "Popular Condo Ville (ตึก C3)", dist: "~1.2 กม.", rating: 3.8, price: 850, mapQuery: "Popular Condo Ville Muang Thong Thani", reason: "ที่พักงบประหยัดที่สุดที่แฟนคอนไปพักกันเป็นประจำ ใกล้ร้านอาหารตึกป๊อปปูล่าให้แวะรอคนบางลงหลังคอนเลิก", image: "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=700&q=80&fit=crop", bookingUrl: "https://www.agoda.com/great-location-at-impact-arena-muangthong-thani/hotel/nonthaburi-th.html" },
      { id: "h4", name: "Amari Don Muang Airport", dist: "~9.5 กม. (นั่งรถ 20-25 นาที)", rating: 4.8, price: 2400, mapQuery: "Amari Don Muang Airport Bangkok", reason: "รีวิวดีที่สุดในระดับพรีเมียม เหมาะถ้าเดินทางต่อสนามบินดอนเมืองวันรุ่งขึ้น เลี่ยงย่านเมืองทองที่รถแน่นช่วงเลิกงาน", image: "https://media.onyx-hospitality.com/-/media/project/amari/amari-don-muang-airport-bangkok/special-offers/outdoor-swimming-pool_sun-loungers.jpg", bookingUrl: "https://www.agoda.com/amari-don-muang-airport-bangkok-hotel/hotel/bangkok-th.html" },
    ],
    transit: {
      bts: "นั่ง BTS สายสีชมพู (Pink Line) ลงที่ สถานีเมืองทองธานี (MT01) → เปลี่ยนขบวนเข้า สถานีอิมแพ็คเมืองทองธานี → เดินผ่านทางเชื่อม IMPACT CHALLENGER HALL 1 → THE PORTAL → IMPACT ARENA",
      public: "รถเมล์สาย 166 จากอนุสาวรีย์ชัยฯ ฝั่งเกาะพหลโยธิน ผ่านหน้า IMPACT ARENA โดยตรง | รถเมล์สาย 52 จากอนุสาวรีย์ชัยฯ ต่อรถสองแถว | รถตู้เมืองทองธานีจากอนุสาวรีย์ชัยฯ ฝั่งเกาะพหลโยธิน | รถตู้เมืองทองธานีจาก BTS หมอชิต ฝั่งจตุจักร",
      driving: "ขับมาตามถนนแจ้งวัฒนะ หรือทางด่วนศรีรัช เข้า IMPACT ARENA เมืองทองธานี จอดได้ที่ลานจอดฝั่ง Challenger หรือลานจอดหน้าอารีน่า ช่วงเย็นก่อนงานรถจะแน่นเร็ว แนะนำมาถึงก่อนประตูเปิดอย่างน้อย 1 ชม.",
      grab: "ตั้งจุดรับ-ส่งที่ลานจอดฝั่ง Challenger เพื่อเลี่ยงความแน่นหน้าฮอลล์หลัก ขาไปเรียกล่วงหน้า ขากลับให้เดินออกมาสัก 5-10 นาทีก่อนเรียกรถ เพื่อเลี่ยงช่วงพีค",
      returnNote: "คอนมักเลิกประมาณ 21:00-21:30 น. ถ้า BTS สายสีชมพูใกล้ปิด (ส่วนใหญ่ปิดราวๆ 24:00 น.) ให้เผื่อเวลาเดินออกจากฮอลล์ 10-15 นาที หากคิวรถแน่นเกินไป แนะนำนั่งรอที่ร้านอาหารโซนตึกป๊อปปูล่าประมาณ 30-60 นาทีให้คนบางลงก่อน แล้วเรียกวินมอเตอร์ไซค์ที่มีป้ายราคาชัดเจนเท่านั้น",
    },
    weatherNote: "พฤศจิกายนเป็นช่วงเปลี่ยนจากฤดูฝนเข้าสู่ฤดูหนาวของกรุงเทพฯ ปริมาณฝนมักลดลงชัดเจนเทียบกับ ก.ย.-ต.ค. กลางวันยังร้อนอบอ้าวได้ ส่วนช่วงค่ำอาจมีลมโกรกเย็นในฮอลล์แอร์ แนะนำพกเสื้อกันหนาวบางๆ ติดตัว และร่มพับสำรองไว้เผื่อฝนหลงฤดู",
    checklistExtra: [],
  },
  {
    id: "theweeknd",
    name: "The Weeknd: After Hours Til Dawn Tour",
    venueName: "ราชมังคลากีฬาสถาน",
    venueQuery: "Rajamangala National Stadium Bangkok",
    doorTime: "17:00 น.",
    showTime: "19:50 น.",
    isOutdoor: true,
    rounds: [
      { key: "sun", label: "วันอาทิตย์ที่ 11 ตุลาคม 2569", date: "2026-10-11T19:50:00+07:00" },
      { key: "mon", label: "วันจันทร์ที่ 12 ตุลาคม 2569", date: "2026-10-12T19:50:00+07:00" },
      { key: "tue", label: "วันอังคารที่ 13 ตุลาคม 2569", date: "2026-10-13T19:50:00+07:00" },
    ],
    prices: [
      { zone: "VIP1 · Ultimate Package (N1E / N1H)", price: 21935, type: "VIP", color: "#1E3A8A", perks: "ที่นั่ง Zone N1E / N1H ใกล้เวทีที่สุด + สิทธิ์ Early Entry + VIP Package พิเศษ", hasSoundcheck: false, hasEarlyEntry: true },
      { zone: "VIP2 · Gold Lounge (N1E–N1H)", price: 17935, type: "VIP", color: "#1D4ED8", perks: "ที่นั่ง Zone N1E–N1H แถวหน้าใกล้สเตจ + Gold Lounge VIP Package ของที่ระลึก", hasSoundcheck: false, hasEarlyEntry: true },
      { zone: "VIP3 · Early Entry Package (SL/SR)", price: 11335, type: "VIP", color: "#0369A1", perks: "สิทธิ์เข้าโซนยืน SL/SR ก่อนใคร ไม่มีพื้นที่จองเฉพาะ แต่ได้จับตำแหน่งหน้าสุด", hasSoundcheck: false, hasEarlyEntry: true },
      { zone: "Seated CAT 5 (วงใน E1/W1)", price: 8935, type: "Seated", color: "#2563EB", perks: "ที่นั่งอัฒจันทร์วงในมองเห็นเวทีระดับสายตาชัดเจน ราคาสูงสุดในกลุ่มบัตรนั่ง" },
      { zone: "Seated CAT 4 (E2/W2 กลาง-ใน)", price: 6835, type: "Seated", color: "#3B82F6", perks: "ที่นั่งอัฒจันทร์กลาง-ใน มุมมองครอบคลุมทั้งเวทีและ runway" },
      { zone: "Early Entry Standing (SL / SR)", price: 5335, type: "Standing", color: "#0EA5E9", perks: "บัตรยืน SL/SR พร้อมสิทธิ์เข้าก่อน จับตำแหน่งแถวหน้าได้ดีกว่า General", hasEarlyEntry: true },
      { zone: "Seated CAT 3 (E3/W3 กลาง-นอก)", price: 4835, type: "Seated", color: "#60A5FA", perks: "ที่นั่งอัฒจันทร์กลาง-นอก มุมมองเห็นภาพรวมทั้งสเตเดียมได้ดี" },
      { zone: "Standing SL / SR", price: 4335, type: "Standing", color: "#38BDF8", perks: "โซนยืน SL/SR หน้าสเตจ ราคาบัตรทั่วไป บรรยากาศดีที่สุดในกลุ่มบัตรยืน" },
      { zone: "Seated CAT 2 (S/N วงนอก)", price: 3835, type: "Seated", color: "#93C5FD", perks: "ที่นั่งฝั่งข้างและวงนอก ราคาประหยัด เห็นภาพรวมสเตเดียมทั้งหมด" },
      { zone: "Seated CAT 1 (วงนอกสุด)", price: 2835, type: "Seated", color: "#BFDBFE", perks: "ราคาประหยัดที่สุด บางมุมอาจเป็น Restricted View เหมาะสำหรับงบจำกัด" },
    ],
    hotels: [
      { id: "bm1", name: "Baan Thai Boutique", dist: "~0.72 กม.", rating: 4.8, price: 3200, mapQuery: "Baan Thai Boutique Bangkok", reason: "ที่พักบูทีคระดับพรีเมียม ใกล้ราชมังคลาที่สุด เดินถึงสนามได้สบาย ห้องสวยและบริการดีเยี่ยม", image: "https://ak-d.tripcdn.com/images/1mc1312000aespg85476D_R_960_660_R5_D.jpg", bookingUrl: "https://www.agoda.com/baan-thai-boutique-hotel/hotel/bangkok-th.html" },
      { id: "bm2", name: "Livotel Hotel Hua Mak Bangkok", dist: "~1.7 กม.", rating: 4.2, price: 1600, mapQuery: "Livotel Hotel Hua Mak Bangkok", reason: "เช็คอินได้ดึก มีสระว่ายน้ำและฟิตเนส เหมาะพักผ่อนหลังคอนกลางแจ้งที่เหนื่อยได้เต็มที่", image: "https://ak-d.tripcdn.com/images/1mc4v12000guebddtEE78_R_500_400_R5.webp", bookingUrl: "https://www.agoda.com/livotel-hotel-hua-mak-bangkok/hotel/bangkok-th.html" },
      { id: "bm3", name: "Regent Ramkhamhaeng 22", dist: "~0.97 กม.", rating: 4.0, price: 1300, mapQuery: "Regent Ramkhamhaeng 22 Hotel Bangkok", reason: "ห้องกว้างขวาง มีที่จอดรถเยอะ ราคาคุ้มค่าดีสำหรับคอนสเตเดียม", image: "https://ak-d.tripcdn.com/images/1mc5e12000ia46tk1934F_R_960_660_R5_D.jpg", bookingUrl: "https://www.agoda.com/regent-ramkhamhaeng-22/hotel/bangkok-th.html" },
      { id: "bm4", name: "Mintel Huamark", dist: "~2 กม.", rating: 4.3, price: 900, mapQuery: "Mintel Huamark Hotel Bangkok", reason: "งบน้อยที่สุดแต่ดีไซน์โมเดิร์น มีร้านสะดวกซื้อใกล้เคียง เหมาะถ้าอยากประหยัดงบมาซื้อ merch เพิ่ม", image: "https://ak-d.tripcdn.com/images/0582412000mg32h751841_R_960_660_R5_D.jpg", bookingUrl: "https://www.agoda.com/mintel/hotel/bangkok-th.html" },
    ],
    transit: {
      public: "ARL: ลงสถานีหัวหมาก (A4) หรือสถานีรามคำแหง ประตู 1 → ต่อแท็กซี่/มอเตอร์ไซค์/รถเมล์/สองแถวเข้าสนาม | BTS: ลงพญาไท → ต่อ ARL → หัวหมาก (A4) หรือรามคำแหง ประตู 1 | MRT สีน้ำเงิน: ลงเพชรบุรี → ต่อ ARL มักกะสัน → หัวหมาก หรือรามคำแหง | MRT สีเหลือง: ลงมหาดไทย หรือลาดพร้าว 101 → ต่อรถเข้าสนาม | รถเมล์ที่ผ่านสนาม: สาย 22, 60, 71, 92, 93, 95ก, 115, 126, 137, 168, 545",
      boat: "ขึ้นเรือโดยสารคลองแสนแสบ ลงที่ท่าเรือมหาวิทยาลัยรามคำแหง หรือท่าเรือมหาดไทย → เดินตามถนนรามคำแหงและข้ามสะพานเข้าสู่สนามราชมังคลากีฬาสถาน",
      driving: "ที่จอดรถใกล้เคียง: เทสโก้ โลตัส บางกะปิ (~1,170 คัน), เดอะมอลล์ บางกะปิ (~3,000 คัน) คอนเสิร์ตกลางแจ้ง 2 วันรถจะแน่นมาก แนะนำมาก่อนเวลาอย่างน้อย 2 ชม.",
      grab: "ตั้งจุดรับ-ส่งที่ห้างใกล้เคียงแทนหน้าสนาม เลี่ยงช่วงคนออกพร้อมกัน คิว Grab กลางแจ้งจะพีคกว่าคอนในฮอลล์มาก",
      returnNote: "หลังจบการแสดง หน้าสนามราชมังคลา ถนนรามคำแหง มีบริการรถสองแถวและมอเตอร์ไซค์รับส่ง ARL หัวหมาก / MRT พระราม 9 (มีค่าบริการ) คอนสเตเดียมกลางแจ้งตุลาคมอาจเลิกดึก เผื่อแผนสำรองถ้า ARL ใกล้ปิด แนะนำพักค้างคืนใกล้สนามถ้าเดินทางไกล",
    },
    weatherNote: "ตุลาคมอยู่ในช่วงปลายฤดูฝนของกรุงเทพฯ ราชมังคลาเป็นสเตเดียมกลางแจ้ง โอกาสฝนตกช่วงเย็นมีค่อนข้างสูง แนะนำพกร่มพับหรือเสื้อกันฝนแบบพกพาติดตัวไว้เผื่อฉุกเฉิน อุณหภูมิช่วงค่ำเริ่มเย็นลงบ้างหลัง 20:00 น.",
    checklistExtra: [
      { text: "ร่มพับหรือเสื้อกันฝนแบบพกพา (ต.ค. ยังมีฝนได้)", pending: false },
      { text: "พาวเวอร์แบงก์ ≤ 20,000 mAh สำหรับโชว์ที่ยาวหลายชั่วโมง", pending: false },
    ],
  },
];
